/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

_DWORD sub_402800(); // weak
_DWORD sub_402FC9(); // weak
void sub_403021();
int sub_403039();
_DWORD sub_4032DB(); // weak
_DWORD sub_4033FF(); // weak
_DWORD sub_403B9D(); // weak
_DWORD sub_403DDE(); // weak
_DWORD sub_404206(); // weak
_DWORD sub_404326(); // weak
_DWORD sub_404446(); // weak
_DWORD sub_404566(); // weak
_DWORD sub_40479F(); // weak
_DWORD sub_405726(); // weak
_DWORD sub_405E13(); // weak
_DWORD sub_405F3E(); // weak
_DWORD sub_40608C(); // weak
_DWORD sub_406360(); // weak
_DWORD sub_40648F(); // weak
_DWORD sub_4065C2(); // weak
_DWORD sub_4066E9(); // weak
_DWORD sub_40682A(); // weak
_DWORD sub_406951(); // weak
_DWORD sub_406A7C(); // weak
_DWORD sub_406BA3(); // weak
int sub_406BFB();
BOOL sub_406CB8();
int __cdecl sub_40D752(char *Buffer, size_t BufferCount, char *Format, va_list ArgList); // idb
// int __usercall sub_40D778@<eax>(int a1@<eax>, int a2@<ecx>, __int32 a3@<ebp>);
// int __usercall sub_40D7A4@<eax>(int a1@<ebp>);
// int __usercall sub_40D7A8@<eax>(int a1@<ebp>);
// __time32_t __cdecl time(__time32_t *const Time);
// void __cdecl srand(unsigned int Seed);
// void *__cdecl memmove(void *, const void *Src, size_t Size);
// BOOL __stdcall SetConsoleCursorPosition(HANDLE hConsoleOutput, COORD dwCursorPosition);
// int __cdecl vsnprintf(char *const Buffer, const size_t BufferCount, const char *const Format, va_list ArgList);
void sub_44F05E();
_DWORD __cdecl sub_44F9BF(_DWORD); // weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_4012A8; // weak
_UNKNOWN loc_402EFA; // weak
_UNKNOWN loc_4046D0; // weak
_UNKNOWN loc_405AFC; // weak
int dword_40E09C = 0; // weak
int dword_40E0A0 = 0; // weak
int dword_40E0A4 = 0; // weak
int dword_40E0A8 = 0; // weak
HANDLE hConsoleOutput = NULL; // idb
int dword_40E50C = 0; // weak
int dword_42E50C; // weak
char byte_44F054 = '\0'; // weak
char byte_44F057 = '\x03'; // weak
char byte_44F059 = '\x05'; // weak
char byte_44F05C = '\b'; // weak
_UNKNOWN loc_44F12E; // weak
_UNKNOWN loc_44F19C; // weak


//----- (00402800) --------------------------------------------------------
#error "40280C: cannot convert to microcode (funcsize=6)"

//----- (00402FC9) --------------------------------------------------------
#error "402FD5: cannot convert to microcode (funcsize=6)"

//----- (00403021) --------------------------------------------------------
void sub_403021()
{
  JUMPOUT(0x403034);
}
// 40302D: control flows out of bounds to 403034

//----- (00403039) --------------------------------------------------------
int sub_403039()
{
  int result; // eax

  do
  {
    result = 697;
    if ( (unsigned int)byte_44F054 >= 0x2B9 )
      break;
    result = byte_44F05C;
    if ( byte_44F05C <= byte_44F057 )
      break;
    result = ((int (*)(void))loc_44F12E)();
    if ( !result )
      break;
    result = ((int (__cdecl *)(int, int))loc_44F19C)(31, 1);
    if ( !result )
      break;
    result = byte_44F059;
  }
  while ( byte_44F059 );
  return result;
}
// 44F054: using guessed type char byte_44F054;
// 44F057: using guessed type char byte_44F057;
// 44F059: using guessed type char byte_44F059;
// 44F05C: using guessed type char byte_44F05C;

//----- (004032DB) --------------------------------------------------------
#error "4032E7: cannot convert to microcode (funcsize=6)"

//----- (004033FF) --------------------------------------------------------
#error "40340B: cannot convert to microcode (funcsize=6)"

//----- (00403B9D) --------------------------------------------------------
#error "403BA9: cannot convert to microcode (funcsize=6)"

//----- (00403DDE) --------------------------------------------------------
#error "403DEA: cannot convert to microcode (funcsize=6)"

//----- (00404206) --------------------------------------------------------
#error "404212: cannot convert to microcode (funcsize=6)"

//----- (00404326) --------------------------------------------------------
#error "404332: cannot convert to microcode (funcsize=6)"

//----- (00404446) --------------------------------------------------------
#error "404452: cannot convert to microcode (funcsize=6)"

//----- (00404566) --------------------------------------------------------
#error "404572: cannot convert to microcode (funcsize=6)"

//----- (0040479F) --------------------------------------------------------
#error "4047AB: cannot convert to microcode (funcsize=6)"

//----- (00405726) --------------------------------------------------------
#error "405732: cannot convert to microcode (funcsize=6)"

//----- (00405E13) --------------------------------------------------------
#error "405E1F: cannot convert to microcode (funcsize=6)"

//----- (00405F3E) --------------------------------------------------------
#error "405F4A: cannot convert to microcode (funcsize=6)"

//----- (0040608C) --------------------------------------------------------
#error "406098: cannot convert to microcode (funcsize=6)"

//----- (00406360) --------------------------------------------------------
#error "40636C: cannot convert to microcode (funcsize=6)"

//----- (0040648F) --------------------------------------------------------
#error "40649B: cannot convert to microcode (funcsize=6)"

//----- (004065C2) --------------------------------------------------------
#error "4065CE: cannot convert to microcode (funcsize=6)"

//----- (004066E9) --------------------------------------------------------
#error "4066F5: cannot convert to microcode (funcsize=6)"

//----- (0040682A) --------------------------------------------------------
#error "406836: cannot convert to microcode (funcsize=6)"

//----- (00406951) --------------------------------------------------------
#error "40695D: cannot convert to microcode (funcsize=6)"

//----- (00406A7C) --------------------------------------------------------
#error "406A88: cannot convert to microcode (funcsize=6)"

//----- (00406BA3) --------------------------------------------------------
#error "406BAF: cannot convert to microcode (funcsize=6)"

//----- (00406BFB) --------------------------------------------------------
int sub_406BFB()
{
  unsigned int v0; // eax
  int v1; // eax
  int v2; // eax
  int v3; // eax
  int v4; // eax
  int (__cdecl *v5)(_DWORD); // eax
  int result; // eax
  int v7; // [esp+4h] [ebp-Ch]
  int (*v8)(void); // [esp+8h] [ebp-8h]
  int v9; // [esp+Ch] [ebp-4h]

  dword_40E50C = 12;
  dword_42E50C = 12;
  v0 = time(0);
  srand(v0);
  v1 = ((int (*)(void))loc_4046D0)();
  v9 = ((int (__cdecl *)(int))loc_402EFA)(v1);
  v2 = ((int (*)(void))loc_405AFC)();
  v8 = (int (*)(void))((int (__stdcall *)(int, int))loc_4012A8)(v9, v2);
  dword_40E09C = v8() % 23 + 1;
  v3 = ((int (*)(void))loc_4046D0)();
  v7 = ((int (__cdecl *)(int))loc_402EFA)(v3);
  v4 = ((int (*)(void))loc_405AFC)();
  v5 = (int (__cdecl *)(_DWORD))((int (__stdcall *)(int, int))loc_4012A8)(v7, v4);
  dword_40E0A0 = v5(v5) % 23 + 1;
  dword_40E0A4 = 0;
  result = 1;
  dword_40E0A8 = 1;
  return result;
}
// 40E09C: using guessed type int dword_40E09C;
// 40E0A0: using guessed type int dword_40E0A0;
// 40E0A4: using guessed type int dword_40E0A4;
// 40E0A8: using guessed type int dword_40E0A8;
// 40E50C: using guessed type int dword_40E50C;
// 42E50C: using guessed type int dword_42E50C;

//----- (00406CB8) --------------------------------------------------------
BOOL sub_406CB8()
{
  COORD v1; // [esp-4h] [ebp-8h] BYREF
  __int16 Src[2]; // [esp+0h] [ebp-4h] BYREF

  Src[0] = 0;
  Src[1] = 2;
  memmove(&v1, Src, 4u);
  return SetConsoleCursorPosition(hConsoleOutput, v1);
}

//----- (0040D752) --------------------------------------------------------
int __cdecl sub_40D752(char *Buffer, size_t BufferCount, char *Format, va_list ArgList)
{
  return vsnprintf(Buffer, BufferCount, Format, ArgList);
}

//----- (0040D778) --------------------------------------------------------
int __usercall sub_40D778@<eax>(int a1@<eax>, int a2@<ecx>, __int32 a3@<ebp>)
{
  void **v3; // ecx
  int (__thiscall *v6)(int); // [esp-4h] [ebp-4h]
  void *retaddr; // [esp+0h] [ebp+0h] BYREF

  v6 = (int (__thiscall *)(int))_InterlockedExchange((volatile __int32 *)&retaddr, a3);
  v3 = &retaddr;
  do
  {
    v3 -= 1024;
    a1 -= 4096;
  }
  while ( a1 >= 4096 );
  return v6(a2);
}

//----- (0040D7A4) --------------------------------------------------------
int __usercall sub_40D7A4@<eax>(int a1@<ebp>)
{
  return *(_DWORD *)(a1 - 20);
}

//----- (0040D7A8) --------------------------------------------------------
int __usercall sub_40D7A8@<eax>(int a1@<ebp>)
{
  return **(_DWORD **)sub_40D7A4(a1);
}

//----- (0044F05E) --------------------------------------------------------
void sub_44F05E()
{
  ;
}

//----- (0044F9BF) --------------------------------------------------------
#error "44FC98: cannot convert to microcode (funcsize=70)"

// nfuncs=71 queued=33 decompiled=33 lumina nreq=0 worse=0 better=0
#error "There were 24 decompilation failure(s) on 33 function(s)"
